### ISSUE TITLE
Pure js version

### ISSUE THREAD

**Issue by gDKdev** [sjmulder/nbt-js#22]
Could you make a pure javascript version (ie no need for node.js).
The decoding from compressed data is not needed.

I'm asking because i'm working on a webview for the supercircuit mod and have no access to a jquery server. I tried to refactor your code before, but i failed.

**Comment by sjmulder** [comment]
Thanks for the request. A pure JS version would be useful but I can’t promise I’ll get it done any time soon. I’ll leave this issue open for anyone interested to pick up.

**Comment by gDKdev** [comment]
I found a pure js version made with emscripten, but it not as easy as this here to use. Maybe because it's ment as a project and not as a library and has no documentation. (This)[https://github.com/iRath96/webNBT] is the repo.

**Comment by sjmulder** [comment]
Good news, I found some time to make NBT.js compatible with browsers. It’s source compatible, so you can just go and include `<script src="nbt.js"></script>`.

Note that
 * This is largely untested
 * You need to pass in data as [ArrayBuffer](https://developer.mozilla.org/nl/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) objects
 * `Writer`’s `buffer` is made private now. Instead, use its `getData()` to get an ArrayBuffer.
 * `writeUncompressed` also gives you an ArrayBuffer instead of a Buffer now
 * Compression only works if `window.zlib` is a zlib module

The changes are in the master branch.

Please let me know how it’s working for you.

**Comment by sjmulder** [comment]
Let’s move the discussion to the existing (Browser support )[https://github.com/sjmulder/nbt-js/issues/5] issue.
