### ISSUE TITLE
What is window.zlib?

### ISSUE THREAD

**Issue by EagleEye7777777** [sjmulder/nbt-js#34]
Hello,

It says that you need to use `window.zlib` in order to compress/decompress in the browser but I cannot for the life of me work out what this is. I am probably just being stupid but if you pointed me in the correct direction it would be much appreciated.

Thanks.

**Comment by gDKdev** [comment]
I used [gunzip.min.js](https://github.com/imaya/zlib.js/blob/master/bin/gunzip.min.js) from [imaya's zlib.js](https://github.com/imaya/zlib.js/blob/master/README.en.md) repo.
But you need to make a small change in the [nbt.js](https://github.com/sjmulder/nbt-js/blob/master/nbt.js) at line 603-609.
Take a look at my repo to see what you need to do: [nbt.js-File](https://github.com/gDKdev/web-scm/blob/master/lib/nbt-sj.js#L603).

What are you planning on doing exactly?

**Comment by EagleEye7777777** [comment]
I am trying to make an online tool that gives a Minecraft schematic file as a download. So do I need to use an existing one, modify the values and then re-compress it ready for download. So do I just use your version of the file and uncomment the commented stuff? Thanks.

**Comment by sjmulder** [comment]
Hi,

Thanks for asking. Technically, what you need is a source compatible replacement for Node.js' zlib module.

This is because NBT.js was only recently ported to the browser and I haven't yet gone and found a good drop in library to include or recommend.

See: https://github.com/sjmulder/nbt-js/issues/30

@gDKdev's suggestion is a good one. If anyone feels like it, feel free to pick up that change, make it detect use either `Zlib.Gunzip` or Node's `zlib` depending on which one is available, and make it a PR for #30.

**Comment by gDKdev** [comment]
@EagleEye7777777 I've uncommented the node.js related stuff and put 1-2 lines under it which calls gunzip.
The only thing I don't know the re-comress stuff works, because I never used it and as far as I know the gunzip-file only can extracr things

**Comment by EagleEye7777777** [comment]
@gDKdev Thanks, I will look into my options for compression.

**Comment by EagleEye7777777** [comment]
@sjmulder Thanks for the explanation. I hope to see the project fully browser implimented soon.

**Comment by gDKdev** [comment]
@EagleEye7777777 I guess there could be something for compression in the same repo as the gunzip.min.js
